In [17]:
# Import Tensorflow 2.x
try:
  %tensorflow_version 1.14
except Exception:
  pass

`%tensorflow_version` only switches the major version: `1.x` or `2.x`.
You set: `1.14`. This will be interpreted as: `1.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [18]:
import tensorflow as tf
print("TF version:", tf.__version__)

TF version: 1.15.0


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.compose import ColumnTransformer

In [20]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [21]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Converting Country to numbers
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# Converting Sex to numbers
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_1.fit_transform(X[:, 2])

X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
# Creating dummy variable for Countries
ct = ColumnTransformer([("one_hot_encoder",
                         OneHotEncoder(),
                         [1])],
                        remainder="passthrough")
X = np.array(ct.fit_transform(X), dtype=np.float)

# Escapling the dummy variale trap
X = X[:, 1:]

In [0]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [0]:
# Import Keras Library
import keras

In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
# Initializing ANN
classifier = Sequential()

In [28]:
# Adding input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11)) 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [29]:
# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [30]:
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [31]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [32]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.




Epoch 1/100





8000/8000 [==============================] - 2s 199us/step - loss: 0.4906 - acc: 0.7955
Epoch 2/100
8000/8000 [==============================] - 1s 119us/step - loss: 0.4293 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4252 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4206 - acc: 0.7995
Epoch 5/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4172 - acc: 0.8244
Epoch 6/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4153 - acc: 0.8281
Epoch 7/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4135 - acc: 0.8301
Epoch 8/100
8000/8000 [==============================] - 1s 133us/step - loss: 0.4122 - acc: 0.8315
Epoch 9/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4110 - acc: 0.8321
Epoch 10/100
8000/8000 [==============================] - 1s 134us/step - loss: 0.4102 - acc:

In [33]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Epoch 1/100
1030/8000 [==>...........................] - ETA: 1s - loss: 0.4085 - acc: 0.8272

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 1s 137us/step - loss: 0.3993 - acc: 0.8339
Epoch 2/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.3994 - acc: 0.8334
Epoch 3/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.3997 - acc: 0.8350
Epoch 4/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.3994 - acc: 0.8330
Epoch 5/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3999 - acc: 0.8357
Epoch 6/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.3997 - acc: 0.8347
Epoch 7/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.3996 - acc: 0.8359
Epoch 8/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3995 - acc: 0.8356
Epoch 9/100
8000/8000 [==============================] - 1s 136us/step - loss: 0.3996 - acc: 0.8347
Epoch 10/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4000 - acc: 0.8349
Epoch 11/10

In [0]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [0]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [36]:
cm

array([[1552,   43],
       [ 275,  130]])